---
version: 1.0.3
hassio_api: true
slug: reverse_ssh_relay
name: "Reverse SSH relay"
description: "A reverse SSH relay"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share
options:
  remote_gateway_port: 8123
  remote_address: null
  remote_port: 22
  remote_user: null
  remote_password: null
schema:
  remote_gateway_port: int
  remote_address: str
  remote_port: int
  remote_user: str
  remote_password: str
